@extends('layout')
@section('title', $modules[$module][0])
@section('body')
<div class="app-shell">
    <aside class="sidebar" id="sidebar" aria-label="Navegação principal">
        <a class="brand" href="{{ route('home') }}"><span class="brand-icon"><img src="{{ asset('brand/facilitajud-icon.png') }}" alt="" width="1254" height="1254"></span><span><strong>Facilita<span class="brand-jud">Jud</span></strong><small>Sua rotina, em equilíbrio.</small></span></a>
        <div class="sidebar-divider"></div><span class="nav-label">ÁREA DE TRABALHO</span>
        <nav aria-label="Módulos">
            @foreach($modules as $key => [$label, $subtitle, $icon])
                @if($key === 'configuracoes')<div class="sidebar-divider"></div>@endif
                <a href="{{ route('workspace', ['module' => $key]) }}" class="nav-link {{ $module === $key ? 'active' : '' }}" @if($module === $key) aria-current="page" @endif><span class="nav-icon"><x-icon :name="$icon"/></span><span>{{ $label }}</span>@if($key === 'tarefas')<span class="nav-count" data-pending-count>{{ $pendingCount }}</span>@endif</a>
            @endforeach
        </nav>
        <div class="office-card"><x-icon name="building-2"/><strong>{{ $office->name }}</strong><p>{{ $demo ? 'Área de trabalho demonstrativa' : 'Área de trabalho pessoal' }}</p><a href="{{ route('workspace', ['module' => 'configuracoes']) }}">Meu escritório <x-icon name="arrow-up-right"/></a></div>

    </aside>
    <div class="sidebar-backdrop" hidden></div>
    <main id="conteudo" class="main-content" data-module="{{ $module }}">
        <header class="page-header">
            <div class="page-heading"><button class="icon-button mobile-menu" aria-label="Abrir menu" aria-expanded="false" aria-controls="sidebar"><x-icon name="menu"/></button><div>@unless($module === 'prazos')<div class="eyebrow">{{ $office->name }}</div>@endunless<h1>{{ $module === 'painel' ? 'Olá, '.$actor : $modules[$module][0] }}</h1>@unless($module === 'prazos')<p>{{ $module === 'painel' ? ucfirst(now()->translatedFormat('l, d \d\e F')).' · vamos organizar seu dia.' : $modules[$module][1] }}</p>@endunless</div></div>
            <div class="header-actions">
                @php($createKind = match($module) { 'processos' => 'case', 'clientes' => 'client', 'agenda' => 'appointment', 'prazos' => 'deadline', 'documentos' => 'document', default => 'task' })
                @php($createLabel = match($createKind) { 'case' => 'Adicionar processo', 'client' => 'Adicionar cliente', 'appointment' => 'Agendar compromisso', 'deadline' => 'Registrar prazo', 'document' => 'Adicionar documento', default => 'Nova tarefa' })
                @if(!in_array($module, ['equipe', 'mensagens', 'configuracoes']) && ($isAdmin || ($module === 'documentos' && $access->allows(request(), 'documentos.upload'))))<button class="button primary" data-create="{{ $createKind }}"><x-icon name="plus"/> {{ $createLabel }}</button>@endif
                <a class="avatar" href="{{ route('workspace', ['module' => 'configuracoes']) }}" aria-label="Perfil e configurações">{{ mb_strtoupper(mb_substr(preg_replace('/^Dra?\.\s*/', '', $office->display_name), 0, 1)) }}{{ mb_strtoupper(mb_substr(collect(explode(' ', $office->name))->last(), 0, 1)) }}</a>
            </div>
        </header>

        @if($module === 'painel')
            @php($heroDue = $primaryWork ? \Carbon\Carbon::parse($primaryWork->due_at) : $nextTask?->due_at)
            @php($heroPriority = $primaryWork ? ($heroDue->isToday() || $heroDue->isPast() ? 'Alta' : 'Média') : $nextTask?->priority)
            <section class="summary-grid" aria-label="Prioridades da rotina">
                <article class="surface next-action" id="next-action" data-next-kind="{{ $primaryWork ? 'work' : 'task' }}" data-next-id="{{ $primaryWork?->id ?? $nextTask?->id }}">
                    <div class="card-label"><span><x-icon name="circle-arrow-right"/> Seu próximo passo</span><span id="next-priority" class="badge {{ $heroPriority === 'Alta' ? 'pink' : 'lavender' }}">{{ $primaryWork || $nextTask ? 'Prioridade '.$heroPriority : 'Tudo organizado' }}</span></div>
                    <h2 id="next-title">{{ $primaryWork?->title ?? $nextTask?->title ?? 'Você está em dia com suas tarefas.' }}</h2>
                    <p id="next-context">{{ $primaryWork ? trim(($primaryWork->process_number ?: 'Obrigação do escritório').' · '.($primaryWork->context ?: 'Registre a conferência e o andamento.')) : ($nextTask?->context ?? ($isAdmin ? 'Adicione uma nova tarefa para planejar o próximo passo.' : 'Suas próximas atribuições aparecerão aqui.')) }}</p>
                    <div class="hero-bottom"><span id="next-due" class="due-highlight"><x-icon name="clock-3"/><span><small id="next-due-label">{{ $heroDue ? ($heroDue->isToday() ? 'Vence hoje' : $heroDue->translatedFormat('d M')) : 'Tudo em dia' }}</small><strong id="next-due-time">{{ $heroDue?->format('H:i') ?? '✓' }}</strong></span></span><button class="button primary" id="open-next" @disabled(!$isAdmin && !$primaryWork && !$nextTask)>{{ $primaryWork ? 'Abrir obrigação' : ($nextTask ? 'Abrir tarefa' : 'Criar tarefa') }} <x-icon name="arrow-right"/></button></div>
                </article>
                <a class="surface summary-card" href="{{ route('workspace', ['module' => isset($modules['prazos']) ? 'prazos' : 'configuracoes']) }}"><span class="icon-tile pink"><x-icon name="clock-3"/></span><div class="summary-body"><h2>Prazos hoje</h2><strong class="metric">{{ $dueTodayCount + $queueTodayCount }}</strong><p class="attention">{{ $dueTodayCount + $queueTodayCount ? 'Pendentes para hoje' : 'Tudo em dia para hoje' }} @if($overdueCount) · {{ $overdueCount }} prazos jurídicos em atraso @endif</p><span class="summary-link">{{ isset($modules['prazos']) ? 'Ver prazos' : 'Acessos definidos pelo ADM' }} <x-icon name="arrow-right"/></span></div></a>
                <a class="surface summary-card" href="{{ route('workspace', ['module' => isset($modules['agenda']) ? 'agenda' : 'configuracoes']) }}"><span class="icon-tile lavender"><x-icon name="calendar-days"/></span><div class="summary-body"><h2>Compromissos hoje</h2><strong class="metric">{{ $todayAppointmentsCount }}</strong><p>{{ $todayAppointment ? \Carbon\Carbon::parse($todayAppointment->starts_at)->format('H:i').' · '.$todayAppointment->title : 'Nenhum compromisso para hoje.' }}</p><span class="summary-link">{{ isset($modules['agenda']) ? 'Abrir agenda' : 'Acessos definidos pelo ADM' }} <x-icon name="arrow-right"/></span></div></a>
            </section>
            <div class="dashboard-grid">
                <x-task-list :tasks="$tasks" :pending-count="$pendingCount" :completed-count="$completedCount" home />
                <div class="support-column">
                    <section class="surface compact-surface"><div class="section-head"><h2>Prazos próximos</h2><x-icon name="clock-3"/></div><div class="compact-list">
                        @forelse($deadlines->take(3) as $deadline)
                            @php($due = \Carbon\Carbon::parse($deadline->due_at))
                            <button class="compact-row" data-detail="deadline" data-id="{{ $deadline->id }}"><span><strong>{{ $deadline->title }}</strong><small>{{ $due->isToday() ? 'Hoje' : $due->translatedFormat('d M') }} · {{ $due->format('H:i') }}</small></span><span class="badge {{ $due->isToday() || $due->isPast() ? 'pink' : 'lavender' }}">{{ $due->isToday() ? 'Hoje' : ($due->isPast() ? 'Em atraso' : 'Próximo') }}</span></button>
                        @empty<p class="empty-inline">Nenhum prazo pendente.</p>@endforelse
                    </div><a class="text-link" href="{{ route('workspace', ['module' => isset($modules['prazos']) ? 'prazos' : 'configuracoes']) }}">Ver todos os prazos <x-icon name="arrow-right"/></a></section>
                    <section class="surface compact-surface"><div class="section-head"><h2>Atividade recente</h2><span class="metadata">Escritório</span></div><div class="activity-list" id="activity-list">
                        @forelse($activities as $activity)<div class="activity-row"><span class="icon-tile {{ $activity->kind === 'task' ? 'green' : 'lavender' }}"><x-icon :name="$activity->kind === 'task' ? 'check' : 'file-text'"/></span><span><p>{{ $activity->description }}</p><small>{{ \Carbon\Carbon::parse($activity->created_at)->translatedFormat('d M · H:i') }} · {{ $activity->actor }}</small></span></div>@empty<p class="empty-inline">As próximas atividades aparecerão aqui.</p>@endforelse
                    </div></section>
                </div>
            </div>
        @elseif($module === 'tarefas')
            <div class="toolbar"><div class="tabs" aria-label="Filtrar tarefas"><button class="selected" data-task-filter="pending" aria-pressed="true">Pendentes</button><button data-task-filter="completed" aria-pressed="false">Concluídas</button><button data-task-filter="all" aria-pressed="false">Todas</button></div><label class="search-field"><x-icon name="search"/><input type="search" placeholder="Buscar tarefa" aria-label="Buscar tarefa" data-list-search></label></div>
            <x-task-list :tasks="$tasks" :pending-count="$pendingCount" :completed-count="$completedCount"/>
        @elseif($module === 'processos')
            <div class="toolbar"><h2>Carteira de processos <span class="metadata">{{ $cases->count() }} registros</span></h2><label class="search-field"><x-icon name="search"/><input type="search" placeholder="Buscar processo ou cliente" aria-label="Buscar processo" data-list-search></label></div>
            <div class="surface table-surface"><table class="data-table"><thead><tr><th>Processo</th><th>Cliente</th><th>Situação</th><th>Responsável</th><th><span class="sr-only">Abrir</span></th></tr></thead><tbody>
                @forelse($cases as $case)<tr data-search="{{ mb_strtolower($case->title.' '.$case->number.' '.$case->client_name) }}"><td><button class="table-title" data-detail="case" data-id="{{ $case->id }}">{{ $case->title }}<small>{{ $case->number ?? 'Consultivo / extrajudicial' }}</small></button></td><td data-label="Cliente">{{ $case->client_name }}</td><td data-label="Situação"><span class="badge {{ $case->status === 'Concluído' ? 'green' : 'lavender' }}">{{ $case->status }}</span></td><td data-label="Responsável">{{ $case->responsible }}</td><td><button class="icon-button" data-detail="case" data-id="{{ $case->id }}" aria-label="Abrir {{ $case->title }}"><x-icon name="chevron-right"/></button></td></tr>@empty<tr><td colspan="5" class="empty-inline">Adicione seu primeiro processo para acompanhar a rotina.</td></tr>@endforelse
            </tbody></table></div>
        @elseif($module === 'clientes')
            <div class="toolbar"><h2>Seus clientes <span class="metadata">{{ $clients->count() }} cadastrados</span></h2><label class="search-field"><x-icon name="search"/><input type="search" placeholder="Buscar cliente" aria-label="Buscar cliente" data-list-search></label></div>
            <div class="surface table-surface"><table class="data-table"><thead><tr><th>Cliente</th><th>Contato</th><th>Processos vinculados</th><th><span class="sr-only">Abrir</span></th></tr></thead><tbody>@forelse($clients as $client)<tr data-search="{{ mb_strtolower($client->name.' '.$client->email) }}"><td><button class="table-title" data-detail="client" data-id="{{ $client->id }}">{{ $client->name }}</button></td><td data-label="Contato">{{ $client->email ?? 'Contato não informado' }}<small>{{ $client->phone }}</small></td><td data-label="Processos">{{ $cases->where('client_id', $client->id)->count() }} processos</td><td><button class="icon-button" data-detail="client" data-id="{{ $client->id }}" aria-label="Abrir {{ $client->name }}"><x-icon name="chevron-right"/></button></td></tr>@empty<tr><td colspan="4" class="empty-inline">Adicione um cliente para começar.</td></tr>@endforelse</tbody></table></div>
        @elseif($module === 'agenda')
            <div class="toolbar"><h2>Próximos compromissos</h2><label class="search-field"><x-icon name="search"/><input type="search" placeholder="Buscar compromisso" aria-label="Buscar compromisso" data-list-search></label></div>
            <section class="surface agenda-list">@forelse($appointments as $appointment)@php($date = \Carbon\Carbon::parse($appointment->starts_at))<button class="agenda-row" data-detail="appointment" data-id="{{ $appointment->id }}" data-search="{{ mb_strtolower($appointment->title.' '.$appointment->location) }}"><span class="date-tile"><small>{{ $date->translatedFormat('M') }}</small><strong>{{ $date->format('d') }}</strong></span><span class="agenda-time">{{ $date->format('H:i') }}<small>{{ $date->translatedFormat('l') }}</small></span><span class="grow"><strong>{{ $appointment->title }}</strong><small>{{ $appointment->location }}</small></span><span class="badge lavender">{{ $appointment->kind }}</span><x-icon name="chevron-right"/></button>@empty<div class="empty-state"><x-icon name="calendar-days"/><h3>Sua agenda está livre.</h3><p>Agende uma audiência, reunião ou atendimento.</p></div>@endforelse</section>
        @elseif($module === 'prazos')
            @include('partials.work-queue')
            <div class="deadline-overview"><strong>{{ $deadlines->count() }} <span>prazos jurídicos pendentes</span></strong><span class="metadata">{{ $dueTodayCount }} {{ $dueTodayCount === 1 ? 'vence' : 'vencem' }} hoje</span></div>
            <section class="surface agenda-list">@forelse($deadlines as $deadline)@php($date = \Carbon\Carbon::parse($deadline->due_at))<div class="agenda-row"><span class="date-tile {{ $date->isToday() || $date->isPast() ? 'pink' : '' }}"><small>{{ $date->translatedFormat('M') }}</small><strong>{{ $date->format('d') }}</strong></span><button class="task-content grow" data-detail="deadline" data-id="{{ $deadline->id }}"><strong>{{ $deadline->title }}</strong><small>{{ $deadline->case_title }} · {{ $date->format('H:i') }}</small></button><span class="badge {{ $date->isToday() || $date->isPast() ? 'pink' : 'lavender' }}">{{ $date->isToday() ? 'Vence hoje' : ($date->isPast() ? 'Em atraso' : 'Próximo') }}</span><button class="button subtle" data-complete-deadline="{{ $deadline->id }}">Dar baixa</button></div>@empty<div class="empty-state"><x-icon name="circle-check"/><h3>Nenhum prazo pendente.</h3><p>Registre os próximos prazos do escritório.</p></div>@endforelse</section>
        @elseif($module === 'documentos')
            <div class="toolbar"><h2>Arquivos do escritório</h2><label class="search-field"><x-icon name="search"/><input type="search" placeholder="Buscar documento" aria-label="Buscar documento" data-list-search></label></div>
            <section class="surface agenda-list">@forelse($documents as $document)<a class="agenda-row" href="{{ route('documents.download', $document->id) }}" data-search="{{ mb_strtolower($document->name) }}"><span class="icon-tile lavender"><x-icon name="file-text"/></span><span class="grow"><strong>{{ $document->name }}</strong><small>{{ $cases->firstWhere('id', $document->legal_case_id)?->title ?? 'Escritório' }} · {{ number_format($document->size / 1024, 1, ',', '.') }} KB</small></span><span class="metadata">{{ \Carbon\Carbon::parse($document->created_at)->format('d/m/Y') }}</span><x-icon name="download"/></a>@empty<div class="empty-state"><x-icon name="files"/><h3>Seus documentos, organizados.</h3><p>Adicione um arquivo e vincule ao processo quando necessário.</p>@if($access->allows(request(), 'documentos.upload'))<button class="button primary" data-create="document">Adicionar documento</button>@endif</div>@endforelse</section>
        @elseif($module === 'equipe')
            @include('partials.team')
        @elseif($module === 'mensagens')
            <section class="surface conversations"><div class="conversation-contacts">@foreach($clients->filter(fn($client) => $messages->where('client_id', $client->id)->isNotEmpty()) as $client)<button data-conversation="{{ $client->id }}"><span class="avatar neutral">{{ mb_strtoupper(mb_substr($client->name, 0, 1)) }}</span>{{ $client->name }}</button>@endforeach</div><div class="conversation-main"><h2 id="conversation-title">Conversas demonstrativas</h2><p class="page-note">Prévia de organização das conversas. Envio externo ainda não conectado.</p>@foreach($messages as $message)<div class="message-bubble" data-message-client="{{ $message->client_id }}" hidden>{{ $message->body }}<small>{{ \Carbon\Carbon::parse($message->created_at)->format('d/m · H:i') }}</small></div>@endforeach @if($messages->isEmpty())<p class="empty-inline">Nenhuma conversa cadastrada.</p>@endif</div></section>
        @elseif($module === 'configuracoes')
            @if($isAdmin)<section class="surface settings-surface"><h2>Meu escritório</h2><form id="settings-form"><label>Nome de exibição<input name="display_name" value="{{ $office->display_name }}" required maxlength="120"></label><label>Escritório<input name="name" value="{{ $office->name }}" required maxlength="160"></label><label class="switch-label">Destacar prazos próximos<input name="reminders" type="checkbox" role="switch" @checked($office->reminders)></label><p class="metadata">Preferência visual. Notificações por e-mail ainda não estão conectadas.</p><p class="form-error" role="alert" hidden></p><button class="button primary" type="submit"><x-icon name="save"/> Salvar alterações</button></form></section>
            @else<section class="surface settings-surface"><h2>Meu perfil</h2><p>{{ $actor }}</p>@foreach($members as $profile)<p class="metadata">{{ $categories->firstWhere('id', $profile->category_id)?->name ?? 'Associado' }}</p><p>{{ $profile->responsibilities ?: ($categories->firstWhere('id', $profile->category_id)?->responsibilities ?: 'Responsabilidades definidas pelo administrador.') }}</p>@endforeach</section>@endif
            <section class="integration-settings"><h2>Conexões</h2><div><span><strong>Neon Auth</strong><small>Autenticação do escritório</small></span><span class="badge {{ config('facilitajud.neon_url') ? 'green' : 'lavender' }}">{{ config('facilitajud.neon_url') ? 'Configurado' : 'Aguardando configuração' }}</span></div><div><span><strong>Judit</strong><small>Consulta e acompanhamento processual</small></span><span class="badge lavender">Integração planejada</span></div>@unless($demo)<form action="{{ route('logout') }}" method="POST" id="logout-form">@csrf<button class="button subtle" type="submit">Sair da conta <x-icon name="log-out"/></button></form>@endunless</section>
        @endif
        <p class="empty-state search-empty" hidden>Nenhum resultado para esta busca.</p>
        <footer class="page-footer"><span>FacilitaJud · Mais leveza na rotina jurídica</span><span>{{ $demo ? 'Ambiente demonstrativo · Dados fictícios' : 'Área de trabalho protegida' }} · v{{ config('facilitajud.version') }}</span></footer>
    </main>
</div>
@if($module === 'painel' && $primaryWork) @include('partials.work-queue', ['dialogsOnly'=>true]) @endif
@include('partials.dialogs')
@endsection
