<div class="toolbar"><div class="tabs" aria-label="Visualização da agenda"><a class="button {{ request('view') === 'list' ? 'primary' : 'subtle' }}" href="{{ route('workspace', ['module'=>'agenda','view'=>'list','month'=>$calendarMonth->format('Y-m')]) }}">Lista</a><a class="button {{ request('view') !== 'list' ? 'primary' : 'subtle' }}" href="{{ route('workspace', ['module'=>'agenda','month'=>$calendarMonth->format('Y-m')]) }}">Calendário</a></div><button class="button subtle" data-open-calendar-integrations>Integrações</button></div>
<div class="calendar-heading"><a class="icon-button" aria-label="Mês anterior" href="{{ route('workspace', ['module'=>'agenda','view'=>request('view'),'month'=>$calendarMonth->copy()->subMonth()->format('Y-m')]) }}">‹</a><h2>{{ ucfirst($calendarMonth->translatedFormat('F Y')) }}</h2><a class="icon-button" aria-label="Próximo mês" href="{{ route('workspace', ['module'=>'agenda','view'=>request('view'),'month'=>$calendarMonth->copy()->addMonth()->format('Y-m')]) }}">›</a><a class="text-link" href="{{ route('workspace', ['module'=>'agenda','view'=>request('view')]) }}">Hoje</a></div>
@if(request('view') === 'list')
<section class="surface agenda-list">@forelse($appointments as $appointment)@php($date=\Carbon\Carbon::parse($appointment->starts_at))<button class="agenda-row" data-detail="appointment" data-id="{{ $appointment->id }}"><span class="date-tile"><small>{{ $date->translatedFormat('M') }}</small><strong>{{ $date->format('d') }}</strong></span><span class="agenda-time">{{ $date->format('H:i') }}</span><span class="grow"><strong>{{ $appointment->title }}</strong><small>{{ $appointment->location }}</small></span><span class="badge lavender">{{ $appointment->kind }}</span><x-icon name="chevron-right"/></button>@empty<p class="empty-inline">Nenhum compromisso neste mês.</p>@endforelse</section>
@else
<section class="surface calendar-surface" aria-label="Calendário mensal"><div class="calendar-weekdays">@foreach(['Seg','Ter','Qua','Qui','Sex','Sáb','Dom'] as $weekday)<span>{{ $weekday }}</span>@endforeach</div><div class="calendar-grid">
@php($calendarStart=$calendarMonth->copy()->startOfWeek(\Carbon\Carbon::MONDAY))
@php($calendarEnd=$calendarMonth->copy()->endOfMonth()->endOfWeek(\Carbon\Carbon::SUNDAY))
@for($date=$calendarStart->copy();$date->lte($calendarEnd);$date->addDay())
<div class="calendar-day {{ $date->month !== $calendarMonth->month ? 'outside-month' : '' }} {{ $date->isToday() ? 'is-today' : '' }}"><div class="calendar-day-heading"><span>{{ $date->day }}</span>@if($isAdmin)<button class="icon-button" data-calendar-create="{{ $date->format('Y-m-d') }}" aria-label="Agendar em {{ $date->format('d/m') }}">+</button>@endif</div>
@foreach($appointments->filter(fn($item)=>\Carbon\Carbon::parse($item->starts_at)->isSameDay($date)) as $appointment)<button class="calendar-event" data-detail="appointment" data-id="{{ $appointment->id }}"><small>{{ \Carbon\Carbon::parse($appointment->starts_at)->format('H:i') }}</small><span>{{ $appointment->title }}</span></button>@endforeach</div>
@endfor</div></section>
@endif
<dialog id="calendar-integrations" aria-labelledby="calendar-integrations-title"><div class="dialog-head"><div><h2 id="calendar-integrations-title">Integrações da agenda</h2><p>Conecte seus calendários ao escritório.</p></div><button class="icon-button" data-close-dialog aria-label="Fechar integrações">×</button></div>@foreach(['Google Calendar','Calendário Apple','Microsoft Outlook'] as $provider)<button class="integration-provider" data-calendar-provider="{{ $provider }}"><span>{{ $provider }}</span><span class="badge lavender">Em desenvolvimento</span><x-icon name="chevron-right"/></button>@endforeach<p id="calendar-integration-feedback" class="page-note" role="status" hidden></p></dialog>
