<dialog id="editor-dialog" aria-labelledby="editor-title"><div class="dialog-head"><div><h2 id="editor-title">Nova tarefa</h2><p>{{ $office->name }}</p></div><button class="icon-button" data-close-dialog aria-label="Fechar"><x-icon name="x"/></button></div><form id="editor-form"><div id="editor-fields"></div><p class="form-error" role="alert" hidden></p><div class="dialog-actions"><button class="button subtle" type="button" data-close-dialog>Cancelar</button><button class="button primary" type="submit" id="editor-submit">Criar tarefa</button></div></form></dialog>
<dialog id="detail-dialog" aria-labelledby="detail-title"><div class="dialog-head"><div><span class="eyebrow" id="detail-kind">Detalhes</span><h2 id="detail-title">Carregando detalhes</h2></div><button class="icon-button" data-close-dialog aria-label="Fechar detalhes"><x-icon name="x"/></button></div><div id="detail-content"></div><div class="dialog-actions" id="detail-actions"></div></dialog>

<template id="case-options"><option value="">Sem processo vinculado</option>@foreach($cases as $case)<option value="{{ $case->id }}">{{ $case->title }} · {{ $case->client_name }}</option>@endforeach</template>
<template id="client-options"><option value="">Selecione um cliente</option>@foreach($clients as $client)<option value="{{ $client->id }}">{{ $client->name }}</option>@endforeach</template>

<template id="form-task"><label>Tarefa<input name="title" placeholder="O que precisa ser feito?" required maxlength="200"></label><div class="form-grid"><label>Prazo<input name="due_at" type="datetime-local" value="{{ now()->setTime(17, 0)->format('Y-m-d\TH:i') }}" required></label><label>Prioridade<select name="priority"><option>Alta</option><option selected>Média</option><option>Baixa</option></select></label></div><label>Processo<select name="legal_case_id" data-options="case"></select></label><label>Contexto ou observação<textarea name="context" placeholder="Somente os detalhes que ajudam a executar" maxlength="2000" rows="3"></textarea></label></template>
<template id="form-client"><label>Nome do cliente<input name="name" required maxlength="200" placeholder="Nome completo ou razão social"></label><div class="form-grid"><label>E-mail<input name="email" type="email" maxlength="200"></label><label>Telefone<input name="phone" type="tel" maxlength="30"></label></div><label>Observações<textarea name="notes" maxlength="2000" rows="3"></textarea></label></template>
<template id="form-case"><label>Nome do processo ou assunto<input name="title" required maxlength="200" placeholder="Ex.: Ação de indenização"></label><label>Número do processo<input name="number" pattern="[0-9]{7}-[0-9]{2}\.[0-9]{4}\.[0-9]\.[0-9]{2}\.[0-9]{4}" placeholder="0000000-00.0000.0.00.0000"><small>Deixe vazio para assuntos consultivos ou extrajudiciais.</small></label><label>Cliente<select name="client_id" data-options="client" required></select></label><label>Vara ou local<input name="court" required maxlength="200" placeholder="Ex.: 3ª Vara Cível · São Paulo"></label><label>Situação<select name="status"><option>Em andamento</option><option>Aguardando audiência</option><option>Concluído</option></select></label>@if($clients->isEmpty())<p class="page-note">Cadastre um cliente no módulo Clientes antes de adicionar o processo.</p>@endif</template>
<template id="form-appointment"><label>Compromisso<input name="title" required maxlength="200" placeholder="Ex.: Reunião com cliente"></label><div class="form-grid"><label>Data e horário<input name="starts_at" type="datetime-local" required></label><label>Tipo<select name="kind"><option>Reunião</option><option>Audiência</option><option>Atendimento</option></select></label></div><label>Local ou link da reunião<input name="location" required maxlength="200"></label><label>Processo<select name="legal_case_id" data-options="case"></select></label></template>
<template id="form-deadline"><label>Prazo<input name="title" required maxlength="200" placeholder="Ex.: Apresentar contestação"></label><label>Vencimento<input name="due_at" type="datetime-local" required></label><label>Processo<select name="legal_case_id" data-options="case" required></select></label><p class="page-note">Informe o prazo conferido pelo responsável. O sistema não calcula prazos processuais automaticamente.</p></template>
<template id="form-document"><label>Arquivo<input name="file" type="file" accept=".pdf,.doc,.docx,.txt,.jpg,.jpeg,.png" required><small>PDF, Word, texto ou imagem · até 10 MB.</small></label><label>Processo<select name="legal_case_id" data-options="case"></select></label><p class="page-note">O documento ficará disponível somente neste escritório.</p></template>
