<div id="meetings-module" data-consented="{{ $meetingConsented ? '1' : '0' }}" data-consent-version="{{ $meetingConsentVersion }}">
<div class="toolbar"><h2>{{ $meetings->total() }} reuniões <span class="metadata">Vinculadas à agenda</span></h2><button type="button" class="text-link" id="meeting-open-terms">Termos de gravação</button></div>
<p class="page-note">Eventos do tipo Reunião aparecem aqui automaticamente. Registre a conversa e reúna as decisões no mesmo lugar.</p>
<section id="meeting-recorder" class="surface meeting-recorder" aria-label="Gravação da reunião" hidden>
<div class="recording-heading"><span id="meeting-recording-dot" class="recording-dot" aria-hidden="true"></span><div><strong id="meeting-recording-state">Gravação em andamento</strong><p id="meeting-recording-title"></p></div><strong id="meeting-timer" class="recording-timer">00:00</strong></div>
<p id="meeting-live-notice">O microfone está ativo. Todos os participantes devem saber que a reunião está sendo gravada.</p>
<p id="meeting-upload-status" class="metadata" role="status">O áudio é salvo em pequenos trechos.</p>
<div class="meeting-recorder-actions"><button class="button primary" id="meeting-stop">Encerrar e salvar</button><button class="button subtle" id="meeting-retry" hidden>Tentar salvar novamente</button></div>
<p id="meeting-recording-error" class="form-error" role="alert" hidden></p>
</section>
<section class="surface meeting-list">
@forelse($meetings as $meeting)
<details class="meeting-item"><summary><span class="date-tile"><small>{{ \Carbon\Carbon::parse($meeting->starts_at)->translatedFormat('M') }}</small><strong>{{ \Carbon\Carbon::parse($meeting->starts_at)->format('d') }}</strong></span><span class="grow"><strong>{{ $meeting->title }}</strong><small>{{ \Carbon\Carbon::parse($meeting->starts_at)->format('d/m/Y · H:i') }} · {{ $meeting->location }}</small></span><span class="badge lavender">{{ ($meetingRecordings[$meeting->id] ?? collect())->count() }} gravações</span><x-icon name="chevron-right"/></summary>
<div class="meeting-content"><div class="meeting-actions">@if($access->allows(request(),'agenda.view'))<button class="button subtle" data-detail="appointment" data-id="{{ $meeting->id }}">Detalhes do compromisso</button><a class="text-link" href="{{ route('workspace',['module'=>'agenda','month'=>\Carbon\Carbon::parse($meeting->starts_at)->format('Y-m')]) }}">Ver na agenda</a>@endif
@if($access->allows(request(),'reunioes.record'))<button class="button primary" data-record-meeting="{{ $meeting->id }}" data-meeting-title="{{ $meeting->title }}">Gravar reunião</button>@endif</div>
<p class="page-note">Capture o microfone deste dispositivo. Em videoconferências, o áudio dos outros participantes não é capturado automaticamente.</p>
@forelse($meetingRecordings[$meeting->id] ?? collect() as $recording)
<article class="meeting-recording"><div class="section-title-row"><h3>Gravação de {{ \Carbon\Carbon::parse($recording->started_at)->format('d/m · H:i') }}</h3><span class="badge {{ $recording->status === 'ready' ? 'green' : 'lavender' }}">{{ match($recording->status) { 'ready'=>'Salva', 'empty'=>'Sem áudio', default=>'Áudio parcial' } }}</span></div>
<p class="metadata">{{ gmdate($recording->duration_seconds >= 3600 ? 'H:i:s' : 'i:s',$recording->duration_seconds) }} · {{ number_format($recording->size/1048576,2,',','.') }} MB · Participantes informados antes da gravação</p>
@if($recording->size > 0)<audio controls preload="none" aria-label="Áudio da reunião {{ $meeting->title }}" src="{{ route('meetings.audio',['id'=>$recording->id]) }}"></audio><a class="text-link" href="{{ route('meetings.audio',['id'=>$recording->id]) }}" download="reuniao-{{ $recording->id }}.{{ str_contains($recording->mime,'mp4') ? 'm4a' : (str_contains($recording->mime,'ogg') ? 'ogg' : 'webm') }}">Baixar áudio</a>@endif
<form class="meeting-notes-form" data-recording-id="{{ $recording->id }}"><div class="form-grid"><label>Resumo e anotações<textarea name="notes" rows="4" maxlength="30000" @disabled(!$access->allows(request(),'reunioes.record')) placeholder="Registre decisões e pontos importantes.">{{ $recording->notes }}</textarea></label><label>Ata da reunião<textarea name="minutes" rows="4" maxlength="50000" @disabled(!$access->allows(request(),'reunioes.record')) placeholder="Você pode escrever a ata enquanto a geração automática está em desenvolvimento.">{{ $recording->minutes }}</textarea></label></div>@if($access->allows(request(),'reunioes.record'))<button class="button subtle">Salvar anotações e ata</button>@endif<p class="form-error" hidden role="alert"></p></form>
<div class="meeting-ai"><h3>Próximos passos com IA <span class="badge lavender">Em desenvolvimento</span></h3><p>Transcrição do áudio, resumo, ata e sugestões de ações e prazos aparecerão aqui após a conexão com IA. Cada sugestão deverá ser revisada antes de criar tarefas ou alterar prazos.</p><button class="button subtle" data-meeting-ai>Preparar transcrição e ata</button><p class="meeting-ai-feedback metadata" hidden role="status"></p></div>
</article>
@empty<p class="empty-inline">Nenhuma gravação nesta reunião. Ao gravar, o áudio e as anotações aparecerão aqui.</p>@endforelse
</div></details>
@empty<div class="empty-state"><h2>Sua próxima reunião começa na agenda</h2><p>Agende um evento do tipo Reunião para registrá-lo aqui.</p><a class="button subtle" href="{{ route('workspace',['module'=>'agenda']) }}">Abrir agenda</a></div>@endforelse
</section>
@include('partials.pagination',['paginator'=>$meetings])
</div>
<dialog id="meeting-terms" aria-labelledby="meeting-terms-title"><div class="dialog-head"><div><h2 id="meeting-terms-title">Termos de uso da gravação</h2><p>Leia antes de registrar uma conversa.</p></div><button type="button" class="icon-button" data-close-dialog aria-label="Fechar termos de gravação">×</button></div><div class="meeting-terms-copy"><p>A gravação é opcional. O microfone só será ativado depois que você confirmar o início e autorizar o navegador.</p><p>Antes de começar, informe todos os participantes sobre a gravação, a finalidade do registro e quem poderá acessar o áudio. Confirme que todos estão cientes e concordam. Se alguém não concordar, não inicie ou encerre a gravação.</p><p>Durante a captura, o sistema exibirá um aviso visível. O áudio será armazenado no escritório e poderá ser reproduzido por usuários autorizados. Não grave dados que não sejam necessários para a reunião.</p><p>Transcrição, resumo, ata e sugestões com IA estão em desenvolvimento. Nenhum áudio será enviado a um serviço de IA nesta versão. Quando disponíveis, os resultados precisarão de revisão humana; prazos e tarefas não serão alterados sem validação.</p><p>Mantenha esta página aberta até a confirmação de salvamento. Se a conexão falhar, encerraremos a captura e ofereceremos nova tentativa. O microfone captura o ambiente do dispositivo, não o áudio completo de uma videoconferência automaticamente.</p></div><form id="meeting-consent-form"><label class="permission-toggle"><input type="checkbox" name="accepted" required> Li e estou ciente das condições de gravação.</label><div class="dialog-actions"><button type="button" class="button subtle" data-close-dialog>Agora não</button><button class="button primary">Registrar ciência</button></div><p class="form-error" hidden role="alert"></p></form></dialog>
<dialog id="meeting-start-dialog" aria-labelledby="meeting-start-title"><div class="dialog-head"><div><h2 id="meeting-start-title">Gravar reunião</h2><p id="meeting-start-name"></p></div><button type="button" class="icon-button" data-close-dialog aria-label="Cancelar gravação">×</button></div><p>O áudio será capturado pelo microfone e ficará salvo nesta reunião. Avise todos os participantes antes de continuar.</p><form id="meeting-start-form"><label class="permission-toggle"><input type="checkbox" name="participants_confirmed" required> Informei todos os participantes e confirmei que estão cientes e concordam com a gravação.</label><div class="dialog-actions"><button type="button" class="button subtle" data-close-dialog>Cancelar</button><button class="button primary">Iniciar gravação</button></div><p class="form-error" hidden role="alert"></p></form></dialog>
