<div id="meetings-module" data-sync-channel="facilitajud-meetings-{{ request()->attributes->get('office_id') }}-{{ request()->attributes->get('member_id') }}" data-consented="{{ $meetingConsented ? '1' : '0' }}" data-consent-version="{{ $meetingConsentVersion }}">
<div class="toolbar"><h2>{{ $meetings->total() }} reuniões <span class="metadata">Vinculadas à agenda</span></h2><button type="button" class="text-link" id="meeting-open-terms">Termos de gravação</button></div>
<p class="page-note">Eventos do tipo Reunião aparecem aqui automaticamente. Registre a conversa e reúna as decisões no mesmo lugar.</p>
<section class="surface meeting-list">
@forelse($meetings as $meeting)
<details class="meeting-item" data-meeting-id="{{ $meeting->id }}" @if((int)request('meeting') === $meeting->id) open @endif><summary><span class="date-tile"><small>{{ \Carbon\Carbon::parse($meeting->starts_at)->translatedFormat('M') }}</small><strong>{{ \Carbon\Carbon::parse($meeting->starts_at)->format('d') }}</strong></span><span class="grow"><strong>{{ $meeting->title }}</strong><small>{{ \Carbon\Carbon::parse($meeting->starts_at)->format('d/m/Y · H:i') }} · {{ $meeting->location }}</small></span><span class="badge lavender" data-recording-count="{{ $meeting->id }}">{{ ($meetingRecordings[$meeting->id] ?? collect())->count() }} gravações</span><x-icon name="chevron-right"/></summary>
<div class="meeting-content"><div class="meeting-actions">@if($access->allows(request(),'agenda.view'))<button class="button subtle" data-detail="appointment" data-id="{{ $meeting->id }}">Detalhes do compromisso</button><a class="text-link" href="{{ route('workspace',['module'=>'agenda','month'=>\Carbon\Carbon::parse($meeting->starts_at)->format('Y-m')]) }}">Ver na agenda</a>@endif
@if($access->allows(request(),'reunioes.record'))<button class="button primary" data-record-meeting="{{ $meeting->id }}" data-record-url="{{ route('meetings.record',['id'=>$meeting->id,'page'=>$meetings->currentPage()]) }}" data-meeting-title="{{ $meeting->title }}">Gravar reunião</button>@endif</div>
<p class="page-note">Capture o microfone deste dispositivo. Em videoconferências, o áudio dos outros participantes não é capturado automaticamente.</p>
<div data-meeting-recordings="{{ $meeting->id }}">@include('partials.meeting-recordings',['recordings'=>$meetingRecordings[$meeting->id] ?? collect()])</div>
</div></details>
@empty<div class="empty-state"><h2>Sua próxima reunião começa na agenda</h2><p>Agende um evento do tipo Reunião para registrá-lo aqui.</p><a class="button subtle" href="{{ route('workspace',['module'=>'agenda']) }}">Abrir agenda</a></div>@endforelse
</section>
@include('partials.pagination',['paginator'=>$meetings])
</div>
<dialog id="meeting-terms" aria-labelledby="meeting-terms-title"><div class="dialog-head"><div><h2 id="meeting-terms-title">Termos de uso da gravação</h2><p>Leia antes de registrar uma conversa.</p></div><button type="button" class="icon-button" data-close-dialog aria-label="Fechar termos de gravação">×</button></div><div class="meeting-terms-copy"><p>A gravação é opcional. O microfone só será ativado depois que você confirmar o início e autorizar o navegador.</p><p>Antes de começar, informe todos os participantes sobre a gravação, a finalidade do registro e quem poderá acessar o áudio. Confirme que todos estão cientes e concordam. Se alguém não concordar, não inicie ou encerre a gravação.</p><p>Durante a captura, o sistema exibirá um aviso visível. O áudio será armazenado no escritório e poderá ser reproduzido por usuários autorizados. Não grave dados que não sejam necessários para a reunião.</p><p>Transcrição, resumo, ata e sugestões com IA estão em desenvolvimento. Nenhum áudio será enviado a um serviço de IA nesta versão. Quando disponíveis, os resultados precisarão de revisão humana; prazos e tarefas não serão alterados sem validação.</p><p>A gravação será aberta em uma janela própria. Você pode navegar no sistema enquanto ela permanece aberta. Não feche a janela de gravação antes da confirmação de salvamento. Se a conexão falhar, encerraremos a captura e ofereceremos nova tentativa. O microfone captura o ambiente do dispositivo, não o áudio completo de uma videoconferência automaticamente.</p></div><form id="meeting-consent-form"><label class="permission-toggle"><input type="checkbox" name="accepted" required> Li e estou ciente das condições de gravação.</label><div class="dialog-actions"><button type="button" class="button subtle" data-close-dialog>Agora não</button><button class="button primary">Registrar ciência</button></div><p class="form-error" hidden role="alert"></p></form></dialog>
