<div class="team-page"><div class="toolbar"><h2>Equipe do escritório <span class="metadata">{{ $isAdmin ? 'Administre acessos e responsabilidades' : 'Seu perfil de associado' }}</span></h2></div>
<section class="surface team-list">
@foreach($members as $member)
<details class="team-member"><summary><span class="avatar neutral">{{ mb_strtoupper(mb_substr($member->name,0,1)) }}</span><span class="grow"><strong>{{ $member->name }}</strong><small>{{ $member->email ?: 'Equipe do escritório' }}</small></span><span class="badge {{ $member->account_type === 'admin' ? 'green' : 'lavender' }}">{{ $member->account_type === 'admin' ? 'Administrador' : ($categories->firstWhere('id', $member->category_id)?->name ?? 'Associado') }}</span><x-icon name="chevron-down"/></summary>
@if($isAdmin && $member->account_type !== 'admin')
<form class="team-form" data-team-endpoint="/api/v1/team/members/{{ $member->id }}" data-team-method="PATCH">
<label>Categoria<select name="category_id"><option value="">Associado · acesso básico a obrigações</option>@foreach($categories as $category)<option value="{{ $category->id }}" @selected($member->category_id === $category->id)>{{ $category->name }}</option>@endforeach</select></label>
<label>Responsabilidades individuais<textarea name="responsibilities" maxlength="5000" rows="2" placeholder="Deixe vazio para usar as responsabilidades da categoria">{{ $member->responsibilities }}</textarea></label>
<label class="permission-toggle"><input type="checkbox" name="custom_permissions" @checked($member->permissions !== null)> Personalizar acessos deste associado</label>
<div class="permission-grid">@foreach($permissionOptions as $key=>$label)<label><input type="checkbox" name="permissions[]" value="{{ $key }}" @checked(in_array($key,json_decode($member->permissions ?? '[]',true)))> {{ $label }}</label>@endforeach</div>
<p class="metadata">Sem personalização, o associado acompanha os acessos definidos na categoria. Só vê registros atribuídos a ele.</p><button class="button primary">Salvar associado</button>
</form>
@else<p class="team-responsibilities">{{ $member->account_type === 'admin' ? 'Acesso completo. Gerencia a equipe, as planilhas e as atribuições.' : ($member->responsibilities ?: ($categories->firstWhere('id', $member->category_id)?->responsibilities ?: 'Responsabilidades definidas pelo administrador.')) }}</p>@endif
</details>@endforeach</section>
@if($isAdmin)
<div class="team-management-grid">
<section class="surface settings-surface"><h2>Convidar funcionário</h2><p class="page-note">A pessoa entra como associada ao seu escritório.</p>
<form id="invite-form"><label>Nome<input name="name" required maxlength="120"></label><label>E-mail<input name="email" type="email" required maxlength="200"></label><label>Categoria<select name="category_id"><option value="">Associado · acesso básico a obrigações</option>@foreach($categories as $category)<option value="{{ $category->id }}">{{ $category->name }}</option>@endforeach</select></label><label>Responsabilidades individuais<textarea name="responsibilities" rows="2" maxlength="5000" placeholder="Deixe vazio para seguir a categoria"></textarea></label>
<label class="permission-toggle"><input name="custom_permissions" type="checkbox"> Personalizar acessos do convite</label><div class="permission-grid">@foreach($permissionOptions as $key=>$label)<label><input name="permissions[]" type="checkbox" value="{{ $key }}"> {{ $label }}</label>@endforeach</div>
<button class="button primary">Gerar convite de associado</button><p class="metadata">Compartilhe o link com o e-mail convidado. Válido por 7 dias.</p><input id="invite-url" readonly hidden aria-label="Link do convite"><button class="button subtle" id="copy-invite" type="button" hidden>Copiar link</button></form></section>
<section class="surface settings-surface"><h2>Categorias de acesso</h2><p class="page-note">Crie funções para a sua equipe. Alterações valem imediatamente para quem herda a categoria.</p>
@foreach($categories as $category)<details class="category-details"><summary>{{ $category->name }} <x-icon name="chevron-down"/></summary><form class="team-form" data-team-endpoint="/api/v1/team/categories/{{ $category->id }}" data-team-method="PATCH"><label>Categoria<input name="name" required maxlength="120" value="{{ $category->name }}"></label><label>Responsabilidades<textarea name="responsibilities" rows="2" maxlength="5000">{{ $category->responsibilities }}</textarea></label><div class="permission-grid">@foreach($permissionOptions as $key=>$label)<label><input name="permissions[]" type="checkbox" value="{{ $key }}" @checked(in_array($key,json_decode($category->permissions,true)))> {{ $label }}</label>@endforeach</div><button class="button primary">Salvar categoria</button></form></details>@endforeach
<details class="category-details"><summary>Nova categoria <x-icon name="plus"/></summary><form class="team-form" data-team-endpoint="/api/v1/team/categories" data-team-method="POST"><label>Nome da categoria<input name="name" required maxlength="120" placeholder="Ex.: Assistente jurídico"></label><label>Responsabilidades<textarea name="responsibilities" rows="2" maxlength="5000" placeholder="Ex.: Conferir custas e registrar andamentos"></textarea></label><div class="permission-grid">@foreach($permissionOptions as $key=>$label)<label><input name="permissions[]" type="checkbox" value="{{ $key }}" @checked(in_array($key,\App\Services\WorkspacePermissions::DEFAULTS))> {{ $label }}</label>@endforeach</div><button class="button primary">Criar categoria</button></form></details>
</section></div>
<section class="surface settings-surface process-assignment-note"><div class="section-title-row"><h2>Atribuir processos por planilha</h2><span class="badge lavender">Modelo em definição</span></div><p class="page-note">O ADM importará a planilha de processos e definirá os responsáveis. O formato final será configurado quando o modelo estiver pronto.</p><p class="metadata">Referência: número do processo, cliente, parte contrária, vara/comarca, fase, próximo prazo, situação, responsável, link e movimentações.</p></section>
<section class="surface settings-surface record-assignment-section"><h2>Atribuir tarefas e compromissos</h2><p class="page-note">Escolha o registro e o responsável. Obrigações importadas continuam sendo distribuídas em Prazos.</p><form id="record-assignment"><div class="form-grid"><label>Tipo<select name="kind"><option value="task">Tarefa</option><option value="appointment">Compromisso</option></select></label><label>Registro<select name="record" required>@foreach($tasks as $record)<option data-kind="task" value="{{ $record->id }}">{{ $record->title }}</option>@endforeach @foreach($appointments as $record)<option data-kind="appointment" value="{{ $record->id }}">{{ $record->title }}</option>@endforeach</select></label></div><label>Responsável<select name="assigned_member_id"><option value="">Não atribuído</option>@foreach($members as $member)<option value="{{ $member->id }}">{{ $member->name }}</option>@endforeach</select></label><button class="button primary">Atribuir responsável</button></form></section>
@endif

</div>
